# -*- coding: utf-8 -*-
"""Projeto bradesco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpB4qcAF51mRB0ewewrJNKOj81hBVRzD
"""

language = "pt"

"""1 - Gravação de audio com Python ( e uma pitado de javaScript"""

# all imports
from IPython.display import Javascript, Audio, display
from google.colab import output
from base64 import b64decode
from io import BytesIO
!pip -q install pydub
from pydub import AudioSegment

RECORD = """
const sleep  = time => new Promise(resolve => setTimeout(resolve, time))
const b2text = blob => new Promise(resolve => {
  const reader = new FileReader()
  reader.onloadend = e => resolve(e.srcElement.result)
  reader.readAsDataURL(blob)
})
var record = time => new Promise(async resolve => {
  stream = await navigator.mediaDevices.getUserMedia({ audio: true })
  recorder = new MediaRecorder(stream)
  chunks = []
  recorder.ondataavailable = e => chunks.push(e.data)
  recorder.start()
  await sleep(time)
  recorder.onstop = async ()=>{
    blob = new Blob(chunks)
    text = await b2text(blob)
    resolve(text)
  }
  recorder.stop()
})
"""

def record(sec=5):
  display(Javascript(RECORD))
  js_result = output.eval_js('record(%d)' % (sec*1000))
  audio = b64decode(js_result.split(',')[1])
  file_name = "request_audio.wav"
  with open(file_name, "wb") as f:
    f.write(audio)
    return f'/content/{file_name}'

print("Ouvindo.../n")
record_file = record()
display(Audio(record_file, autoplay=True))

"""2. Reconhecimento de fala com Whisper (OpenAi)"""

!pip install git+https://github.com/openai/whisper.git -q

import whisper


model = whisper.load_model("small")
result = model.transcribe(record_file, fp16=False, language=language)
transcription = result ["text"]
print(transcription)

"""3. Integração com a API no Gemini"""

!pip install -U google-genai

from google import genai

client = genai.Client(api_key="chave da API")

# O ajuste principal está aqui no nome do modelo
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=transcription
)

print(response.text)

"""4. Sintetizando a resposta do Gemini como Voz."""

# 1. Instalação da biblioteca gTTS
!pip install gTTS

from gtts import gTTS
from IPython.display import Audio

# 2. Definição do idioma (Português)
idioma = 'pt'

# 3. Adaptação para o Gemini:
# Usamos 'response.text' que contém a resposta exibida no seu print anterior
print("Convertendo o texto do Gemini em áudio...")
tts = gTTS(text=response.text, lang=idioma, slow=False)

# 4. Salvando o arquivo de áudio
audio_path = 'resposta_gemini.mp3'
tts.save(audio_path)

# 5. Player para ouvir o resultado
print("Sucesso! Clique no play abaixo:")
display(Audio(audio_path, autoplay=True))